services:

  
  postgres:
    image: postgres:16
    container_name: fintrak_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - internal

  pgadmin:
    image: dpage/pgadmin4
    container_name: fintrak_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - internal

  backend:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fintrak_backend
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: https://fintrak.org/api/auth/callback
      FRONTEND_URL: https://fintrak.org
      # ALLOWED_EMAIL: ${ALLOWED_EMAIL}
      PLAID_CLIENT_ID: ${PLAID_CLIENT_ID}
      PLAID_SECRET: ${PLAID_SECRET}
      PLAID_ENVIRONMENT: ${PLAID_ENVIRONMENT}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      ALLOWED_EMAIL: ${ALLOWED_EMAIL}
    depends_on:
      - postgres
    networks:
      - internal

  frontend:
    build:
      context: ./frontend/web
      dockerfile: Dockerfile
    container_name: fintrak_frontend
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - internal

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: fintrak_cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate --config /etc/cloudflared/config.yml run
    volumes:
      - ./.cloudflared:/etc/cloudflared:ro
    depends_on:
      - frontend
    networks:
      - internal

volumes:
  postgres_data:

networks:
  internal:
    driver: bridge
